@startuml
actor Staff
participant ManageAccessoryView
participant AdminAccessoriesController
participant JwtTokenHelper
participant AccessoriesDAO
participant VinfastContext
database Database


Staff -> ManageAccessoryView: 1. Access admin manage accessory page
activate ManageAccessoryView

ManageAccessoryView -> AdminAccessoriesController: 2. Delete "/delete/{adminAccessoryId}"
alt try
    activate AdminAccessoriesController
    AdminAccessoriesController -> JwtTokenHelper: 3. AuthenticateAndAuthorize(HttpContext, 1, 3)
    alt Authentication Failure
        activate JwtTokenHelper
        JwtTokenHelper --> AdminAccessoriesController: 4. (isSuccess = false, errorMessage)
        AdminAccessoriesController --> ManageAccessoryView: 5. Return Unauthorized(401, errorMessage)
        ManageAccessoryView --> Staff: 6. Display error message
        
    else Authentication successfully
        JwtTokenHelper --> AdminAccessoriesController: 7. (isSuccess = true, claims)
        deactivate JwtTokenHelper
        ' complete check authentication
        AdminAccessoriesController -> AccessoriesDAO: 8. GetAccessoryById(adminAccessoryId)
        activate AccessoriesDAO
        
        AccessoriesDAO -> VinfastContext: 9. GetAccessoryById(adminAccessoryId)
        activate VinfastContext
        
        VinfastContext -> Database: 10. Execute Query
        activate Database
        Database --> VinfastContext: 11. Return Accessory Data (Or null)
        deactivate Database
        
        VinfastContext --> AccessoriesDAO: 12. Return Accessory Data (Or null)
        deactivate VinfastContext
        AccessoriesDAO --> AdminAccessoriesController: 13. Return detail accessory (or null)
        deactivate AccessoriesDAO

        alt Accessory not found (AccessoryData == null)
            AdminAccessoriesController --> ManageAccessoryView: 14. Return NotFound(404, "Accessory not found")
            ManageAccessoryView --> Staff: 15.Display error message
        else Accessory is found (AccessoryData != null)
            AdminAccessoriesController -> AccessoriesDAO: 16. DeleteAccessoryById(adminAccessory)
            Activate AccessoriesDAO
            AccessoriesDAO -> VinfastContext: 17. UpdateAccessory(accessoryData)
            activate VinfastContext
            VinfastContext -> Database: 18. Execute Query
            activate Database
            Database --> VinfastContext: 19. Return Accessory Data (Or null)
            deactivate Database
            VinfastContext --> AccessoriesDAO: 20. Return Accessory Data (Or null)
            deactivate VinfastContext
            AccessoriesDAO --> AdminAccessoriesController: 21. Return true/false
            deactivate AccessoriesDAO
            alt update accessory failed 
                AdminAccessoriesController --> ManageAccessoryView: 22. BadRequest(400, "Delete accessory failed")
                ManageAccessoryView --> Staff: 23. Display error message
            else Update accessory successfully
                
                AdminAccessoriesController --> ManageAccessoryView: 30. Return Ok(200, "Delete accessory successfully")
                ManageAccessoryView --> Staff: 31. Display success message
            end
        end
    end
else Catch Exception
    AdminAccessoriesController --> ManageAccessoryView: Return BadRequest(400, exception.Message)
    deactivate AdminAccessoriesController
    ManageAccessoryView --> Staff: Display Display error message
deactivate ManageAccessoryView
end




@enduml