@startuml
actor Staff
participant ManageCarView
participant AdminCarsController
participant AutoMapper
participant JwtTokenHelper
participant CarsDAO
participant VinfastContext
database Database

Staff -> ManageCarView: 1. Access car detail admin page
activate ManageCarView

    ManageCarView -> AdminCarsController: 2. get "/api/AdminGetCarById/{id}"
alt try
    activate AdminCarsController

    AdminCarsController -> JwtTokenHelper: 3. AuthenticateAndAuthorize(HttpContext, 1, 3)
        alt Authentication Failure
            activate JwtTokenHelper
            JwtTokenHelper --> AdminCarsController: 4. (isSuccess = false, errorMessage)
            AdminCarsController --> ManageCarView: 5. return Unauthorized(401, errorMessage)
            ManageCarView --> Staff: 6. Display error message
            
        else Authentication successfully
            JwtTokenHelper --> AdminCarsController: 7. (isSuccess = true, claims)
            deactivate JwtTokenHelper
            
            AdminCarsController -> CarsDAO: 8. AdminGetCarById(int id)
            activate CarsDAO
            
            CarsDAO -> VinfastContext: 9. AdminGetCarById(int id)
            activate VinfastContext
            
            VinfastContext -> Database: 10. Execute query
            activate Database
            Database --> VinfastContext: 11. return car detail data
            deactivate Database
            
            VinfastContext --> CarsDAO: 12. return car detail data
            deactivate VinfastContext
            CarsDAO --> AdminCarsController: 13. return car detail data
            deactivate CarsDAO

            alt No Cars Found
                AdminCarsController --> ManageCarView: 14. return NotFound(404, "Car not found")
                ManageCarView --> Staff: 15. Display error message
            else Cars Found
                AdminCarsController -> AutoMapper: 16. ToAdminCarDTO(carDetailData)
                activate AutoMapper
                AutoMapper --> AdminCarsController: 17. return DTO 
                deactivate AutoMapper
                AdminCarsController --> ManageCarView: 18. return Ok(200, "Get car successfully", DTO)
                ManageCarView --> Staff: 19. Show car detail data
            end
        
    end

else Catch Exception
    AdminCarsController --> ManageCarView: 20. return Badrequest(400, exception.Message)
    deactivate AdminCarsController
    ManageCarView --> Staff: 21. Display error message
deactivate ManageCarView
end

@enduml